import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import * as React from "react";
import { TanstackProvider } from "@/lib/tanstack";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen`}>
				{/* Global background image */}
				<img
					src="https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1600&q=80"
					alt="Finance background"
					className="fixed inset-0 w-full h-full object-cover opacity-40 pointer-events-none select-none z-0"
				/>
				{/* Overlay for readability and partial image reveal */}
				<div className="fixed inset-0 bg-white/90 z-10 pointer-events-none" />
				{/* Gradient mask at the bottom for partial image reveal */}
				<div
					className="fixed inset-0 z-20 pointer-events-none"
					style={{ maskImage: "linear-gradient(to top, black 40%, transparent 100%)", WebkitMaskImage: "linear-gradient(to top, black 40%, transparent 100%)" }}
				/>
				<div className="relative z-30">
					<TanstackProvider>{children}</TanstackProvider>
				</div>
			</body>
		</html>
	);
}
